# Generated by Django 4.1.2 on 2022-10-13 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donuts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('donut_code', models.CharField(max_length=50, unique=True, verbose_name='Donut Code')),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'donut',
                'verbose_name_plural': 'donuts',
                'db_table': 'donuts',
            },
        ),
    ]
